package persistencias;
// Generated 15 feb 2026, 15:25:12 by Hibernate Tools 5.4.33.Final

import java.util.Date;

/**
 * ResultadoComunidad generated by hbm2java
 */
public class ResultadoComunidad implements java.io.Serializable {

	private Long id;
	private PorcentajesRangoedad porcentajesRangoedad;
	private String partido;
	private int votos;
	private Date fechaCalculo;

	public ResultadoComunidad() {
	}

	public ResultadoComunidad(PorcentajesRangoedad porcentajesRangoedad, String partido, int votos) {
		this.porcentajesRangoedad = porcentajesRangoedad;
		this.partido = partido;
		this.votos = votos;
	}

	public ResultadoComunidad(PorcentajesRangoedad porcentajesRangoedad, String partido, int votos, Date fechaCalculo) {
		this.porcentajesRangoedad = porcentajesRangoedad;
		this.partido = partido;
		this.votos = votos;
		this.fechaCalculo = fechaCalculo;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public PorcentajesRangoedad getPorcentajesRangoedad() {
		return this.porcentajesRangoedad;
	}

	public void setPorcentajesRangoedad(PorcentajesRangoedad porcentajesRangoedad) {
		this.porcentajesRangoedad = porcentajesRangoedad;
	}

	public String getPartido() {
		return this.partido;
	}

	public void setPartido(String partido) {
		this.partido = partido;
	}

	public int getVotos() {
		return this.votos;
	}

	public void setVotos(int votos) {
		this.votos = votos;
	}

	public Date getFechaCalculo() {
		return this.fechaCalculo;
	}

	public void setFechaCalculo(Date fechaCalculo) {
		this.fechaCalculo = fechaCalculo;
	}

}
