package persistencias;
// Generated 15 feb 2026, 15:25:12 by Hibernate Tools 5.4.33.Final

import java.util.Date;

/**
 * ResultadoRango generated by hbm2java
 */
public class ResultadoRango implements java.io.Serializable {

	private Long id;
	private String rangoEdad;
	private String partido;
	private int votos;
	private Date fechaCalculo;

	public ResultadoRango() {
	}

	public ResultadoRango(String rangoEdad, String partido, int votos) {
		this.rangoEdad = rangoEdad;
		this.partido = partido;
		this.votos = votos;
	}

	public ResultadoRango(String rangoEdad, String partido, int votos, Date fechaCalculo) {
		this.rangoEdad = rangoEdad;
		this.partido = partido;
		this.votos = votos;
		this.fechaCalculo = fechaCalculo;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getRangoEdad() {
		return this.rangoEdad;
	}

	public void setRangoEdad(String rangoEdad) {
		this.rangoEdad = rangoEdad;
	}

	public String getPartido() {
		return this.partido;
	}

	public void setPartido(String partido) {
		this.partido = partido;
	}

	public int getVotos() {
		return this.votos;
	}

	public void setVotos(int votos) {
		this.votos = votos;
	}

	public Date getFechaCalculo() {
		return this.fechaCalculo;
	}

	public void setFechaCalculo(Date fechaCalculo) {
		this.fechaCalculo = fechaCalculo;
	}

}
