package persistencias;
// Generated 15 feb 2026, 15:25:12 by Hibernate Tools 5.4.33.Final

import java.util.Date;

/**
 * Voto generated by hbm2java
 */
public class Voto implements java.io.Serializable {

	private Long id;
	private PorcentajesRangoedad porcentajesRangoedad;
	private String rangoEdad;
	private String partido;
	private Date fecha;

	public Voto() {
	}

	public Voto(PorcentajesRangoedad porcentajesRangoedad, String rangoEdad, String partido) {
		this.porcentajesRangoedad = porcentajesRangoedad;
		this.rangoEdad = rangoEdad;
		this.partido = partido;
	}

	public Voto(PorcentajesRangoedad porcentajesRangoedad, String rangoEdad, String partido, Date fecha) {
		this.porcentajesRangoedad = porcentajesRangoedad;
		this.rangoEdad = rangoEdad;
		this.partido = partido;
		this.fecha = fecha;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public PorcentajesRangoedad getPorcentajesRangoedad() {
		return this.porcentajesRangoedad;
	}

	public void setPorcentajesRangoedad(PorcentajesRangoedad porcentajesRangoedad) {
		this.porcentajesRangoedad = porcentajesRangoedad;
	}

	public String getRangoEdad() {
		return this.rangoEdad;
	}

	public void setRangoEdad(String rangoEdad) {
		this.rangoEdad = rangoEdad;
	}

	public String getPartido() {
		return this.partido;
	}

	public void setPartido(String partido) {
		this.partido = partido;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
